url: "http://nflix-web:8000"
database:
  host: "pgdb"
  dbname: "nflix"
  user: "postgres"
  password: "qaninja"
api:
  movies: "http://nflix-api-movies:3002"
users:
  gestor:
    email: "sf.rafael20@gmail.com"
    senha: "teste652"
  admin:
    email: "adminteste@gmail.com"
    senha: "teste652"
