---
url: "http://nflix-web:8000"
database:
  host: "pgdb"
  dbname: "nflix"
  user: "postgres"
  password: "qaninja"
api:
  movies: "http://nflix-api-movies:3002"
users:
  cat_manager:
    email: "sf.rafael20@gmail.com"
    pass: "123456"